version: '3.8'

services:
  app:
    build:
      context: backend
    image: modelsafety-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - sqlite_data:/app/data  # SQLite数据文件存储
    env_file:
      - backend/.env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  # 数据库初始化服务
  init_db_service:
    build:
      context: backend
    volumes:
      - ./backend:/app
      - sqlite_data:/app/data  # 共享SQLite数据文件
    command: ["python", "init_db.py"]

  frontend:
    build:
      context: frontend
    image: modelsafety-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - app
    command: ["sh", "-c", "rm -rf node_modules/.vite && npm run dev -- --host 0.0.0.0"]

volumes:
  sqlite_data:  # SQLite数据卷